In [4]:
from PIL import Image
import numpy as np
import torch
from google.colab import files
uploaded = files.upload()


Saving Kanchan Gupta.jpg to Kanchan Gupta.jpg


In [10]:
img = Image.open('Kanchan Gupta.jpg')
c = torch.as_tensor(np.array(img)).float()


In [8]:
#print the shape of the tensor
print(c.shape)

torch.Size([859, 722, 3])


In [11]:
#print the data type
print(c.dtype)

torch.float32


In [15]:
#Basic Operations for tensors
a = torch.arange(10)
b = torch.ones(10)
print(f'{a = }')
print(f'{b = }')

#add the tensors (same can be done for subtract, multiply and divide) - addition can be only done on the tensors with the same shape, expect broadcasting
c = a + b
print(f'{c = }')

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
c = tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [16]:
#timing the operation for tensors

%timeit a + b

5.18 µs ± 63.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
#manipulating tensors and shape

a = torch.arange(6)
print(a.shape)

#now view as 2 by 3 - do not copy the underlying data
print(a.view(2,3))

#using reshape - copy the underlying data as well
print(a.reshape(2,3))

torch.Size([6])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [25]:
#Basic Liner algebra with tensors
#transpose a matric

a = torch.rand(2,3)
print(a)

print(a.mT)  # mt for matrix transpose

tensor([[0.1454, 0.1392, 0.6257],
        [0.4531, 0.4068, 0.1734]])
tensor([[0.1454, 0.4531],
        [0.1392, 0.4068],
        [0.6257, 0.1734]])


In [27]:
#Permuter function

a = torch.rand(2,3,4)
print(a)

print(a.permute(2,0,1)) #data in 3 position will be in first, data in first will be in second and data in second will be in third - (4,2,3) - new shape
print(a.permute(2,0,1).shape)

tensor([[[0.4293, 0.5570, 0.1574, 0.7014],
         [0.1382, 0.8327, 0.9571, 0.5664],
         [0.6480, 0.0759, 0.3098, 0.0702]],

        [[0.1688, 0.7852, 0.1507, 0.0011],
         [0.4401, 0.6244, 0.0846, 0.5533],
         [0.1226, 0.5464, 0.1229, 0.5828]]])
tensor([[[0.4293, 0.1382, 0.6480],
         [0.1688, 0.4401, 0.1226]],

        [[0.5570, 0.8327, 0.0759],
         [0.7852, 0.6244, 0.5464]],

        [[0.1574, 0.9571, 0.3098],
         [0.1507, 0.0846, 0.1229]],

        [[0.7014, 0.5664, 0.0702],
         [0.0011, 0.5533, 0.5828]]])
torch.Size([4, 2, 3])


In [31]:
#learning none
a = torch.arange(6).view(3,2)
print(a[...,None,:,None])
print(a[...,None,:,None].shape)

tensor([[[[0],
          [1]]],


        [[[2],
          [3]]],


        [[[4],
          [5]]]])
torch.Size([3, 1, 2, 1])


In [37]:
#squeezing tensors
a = torch.arange(6).view(3,2,1,1)
print(a)
print(a.shape)
print(a[...,0].shape) # or use print(a.squeeze(-1).shape) - to remove the last dimension

tensor([[[[0]],

         [[1]]],


        [[[2]],

         [[3]]],


        [[[4]],

         [[5]]]])
torch.Size([3, 2, 1, 1])
torch.Size([3, 2, 1])


In [40]:
#Broadcasting

#simple example of broadcasting

x = torch.randn(10,2)
d = torch.zeros(10,10)
for i in range(10):
  for j in range(10):
    d[i,j] = (x[i]-x[j]).pow(2).sum()
print(d)

#use broadcasting to calculate the above
d = (x[:,None,:] - x[None,:,:]).pow(2).sum(-1)
print(d)

tensor([[ 0.0000,  2.4585,  0.3176,  2.4646,  4.9265, 14.4496,  3.1454,  4.6526,
         13.4603, 10.0943],
        [ 2.4585,  0.0000,  3.6790,  0.1118,  0.9441,  5.3397,  0.4260,  9.7599,
          4.4357,  2.8832],
        [ 0.3176,  3.6790,  0.0000,  3.3434,  7.2421, 17.7800,  3.7865,  6.4069,
         15.6669, 11.4456],
        [ 2.4646,  0.1118,  3.3434,  0.0000,  1.6484,  6.2045,  0.1127, 11.0296,
          4.5377,  2.5877],
        [ 4.9265,  0.9441,  7.2421,  1.6484,  0.0000,  2.6792,  2.3787,  9.7090,
          3.7263,  3.6429],
        [14.4496,  5.3397, 17.7800,  6.2045,  2.6792,  0.0000,  6.6002, 21.6941,
          1.3089,  3.1982],
        [ 3.1454,  0.4260,  3.7865,  0.1127,  2.3787,  6.6002,  0.0000, 13.1572,
          4.2198,  2.0657],
        [ 4.6526,  9.7599,  6.4069, 11.0296,  9.7090, 21.6941, 13.1572,  0.0000,
         25.1991, 22.9956],
        [13.4603,  4.4357, 15.6669,  4.5377,  3.7263,  1.3089,  4.2198, 25.1991,
          0.0000,  0.6249],
        [10.0943,  

Matrix multiplication

In [47]:
a = torch.rand(2,4)
b = torch.rand(4,3)
print(a)
print(b)
c = a @ b
print(c.shape)

#print the norm
print(torch.linalg.norm(c))


tensor([[0.7130, 0.1250, 0.0142, 0.9029],
        [0.5756, 0.5339, 0.2957, 0.1340]])
tensor([[7.3861e-01, 7.4933e-01, 4.2588e-01],
        [7.1191e-01, 1.3798e-01, 2.5774e-01],
        [2.3048e-01, 9.5929e-01, 8.2024e-01],
        [1.8197e-02, 1.3512e-01, 2.6882e-04]])
torch.Size([2, 3])
tensor(1.6750)
