In [15]:
import torch
import torch.nn as nn #neural network library
import torch.nn.functional


In [16]:
#define our first linear regression model
model = nn.Linear(10,1)

In [17]:
print(model)

Linear(in_features=10, out_features=1, bias=True)


In [18]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0250, -0.1833,  0.2620,  0.2334,  0.1749,  0.1061, -0.0010, -0.0201,
         -0.0017, -0.0231]], requires_grad=True)
Parameter containing:
tensor([0.0980], requires_grad=True)


In [19]:
x = torch.ones(10)
model(x)

tensor([0.6703], grad_fn=<ViewBackward0>)

Linear Classification using Pytorch

In [41]:
class LinearClassifier(torch.nn.Module):           #any module in pytorch is torch.nn.Module
    def __init__(self, input_dim, output_dim) -> None:
        super().__init__()  # the very first line always call super init, it will tell Pytorch to initialize the module
        self.fc = torch.nn.Linear(input_dim, output_dim)


    def forward(self,x) -> Tensor:
        return nn.functional.sigmoid(self.fc(x))

model = LinearClassifier(10,1)
print(model)
print(model.fc.weight)
print(model.fc.bias)

x = torch.zeros(10)
model(x)



LinearClassifier(
  (fc): Linear(in_features=10, out_features=1, bias=True)
)
Parameter containing:
tensor([[-0.1963, -0.1230, -0.0802, -0.2798,  0.1464, -0.0214, -0.0488, -0.2268,
         -0.3092, -0.2100]], requires_grad=True)
Parameter containing:
tensor([-0.1971], requires_grad=True)


tensor([0.4509], grad_fn=<SigmoidBackward0>)

In [42]:
x = torch.rand(100,10)
model(x)

tensor([[0.2692],
        [0.3431],
        [0.3069],
        [0.2674],
        [0.2939],
        [0.3825],
        [0.2987],
        [0.2498],
        [0.2976],
        [0.2412],
        [0.2795],
        [0.2507],
        [0.2710],
        [0.2961],
        [0.3092],
        [0.2698],
        [0.3160],
        [0.2679],
        [0.3359],
        [0.3053],
        [0.2925],
        [0.3003],
        [0.3586],
        [0.2712],
        [0.2825],
        [0.2917],
        [0.3424],
        [0.3393],
        [0.2559],
        [0.3016],
        [0.3272],
        [0.2505],
        [0.3162],
        [0.3236],
        [0.3635],
        [0.2685],
        [0.2877],
        [0.3259],
        [0.2770],
        [0.3099],
        [0.2908],
        [0.2697],
        [0.2867],
        [0.2393],
        [0.3162],
        [0.2700],
        [0.3601],
        [0.2931],
        [0.2780],
        [0.3691],
        [0.2546],
        [0.3485],
        [0.3005],
        [0.3164],
        [0.3182],
        [0